version: "3.8"

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:14.6-alpine3.17
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_DB: app_db
      SCHEMA: public
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 55433:5432
    restart: unless-stopped

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.3
    depends_on:
      - postgres
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=postgres port=5432 user=postgres password=postgres dbname=app_db
    volumes:
      - ./migrations:/migrations
    command: up

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user


