FROM golang:1.23.4-alpine AS build

WORKDIR /build

COPY ["go.mod", "go.sum", "./"]
RUN go mod download

COPY . ./

RUN go build -o ./bin/app cmd/scheduler/main.go

FROM alpine

COPY --from=build /build/bin/app /

CMD ["/app"]